package ratatoskr

func BuiltInRules() []Rule {
	return []Rule{
		{
			Name:               "laravel-storage-logs",
			Source:             "built-in",
			Category:           CategoryLogs,
			Risk:               RiskSafe,
			PathPatterns:       []string{"storage/logs/*.log"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel writes these logs during normal runtime.",
			Consequence:        "Deleting them removes local log history. Laravel recreates new logs when needed.",
			CleanableByDefault: true,
			RebuildCost:        "none",
			ReclaimDurability:  "temporary",
			PreferredCleanup:   "Use Laravel's normal log rotation or clear stale local logs after review.",
		},
		{
			Name:               "laravel-bootstrap-cache",
			Source:             "built-in",
			Category:           CategoryFrameworkRuntime,
			Risk:               RiskSafe,
			PathPatterns:       []string{"bootstrap/cache/*.php"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel generates these framework cache files.",
			Consequence:        "Deleting them may make the next Laravel command rebuild framework cache.",
			CleanableByDefault: true,
			RebuildCost:        "low",
			ReclaimDurability:  "temporary",
			PreferredCleanup:   "Use Laravel's cache/config clear flows when you need fresh framework cache.",
		},
		{
			Name:               "laravel-compiled-views",
			Source:             "built-in",
			Category:           CategoryFrameworkRuntime,
			Risk:               RiskSafe,
			PathPatterns:       []string{"storage/framework/views/*"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel compiles Blade templates into this directory.",
			Consequence:        "Deleting them may make the next request recompile views.",
			CleanableByDefault: true,
			RebuildCost:        "low",
			ReclaimDurability:  "temporary",
			PreferredCleanup:   "Let Laravel rebuild compiled views on the next request or command.",
		},
		{
			Name:               "laravel-framework-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskSafe,
			PathPatterns:       []string{"storage/framework/cache/*"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel stores generated framework cache entries here.",
			Consequence:        "Deleting them may make Laravel rebuild cache entries.",
			CleanableByDefault: true,
			RebuildCost:        "low",
			ReclaimDurability:  "temporary",
			PreferredCleanup:   "Use Laravel's cache clear flow when stale framework cache is the problem.",
		},
		{
			Name:               "node-build-output",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskSafe,
			PathPatterns:       []string{".next", ".nuxt", "dist", "build", ".turbo", ".vite", "coverage"},
			AppliesWhen:        []string{"package.json or a known lockfile exists"},
			Exclusions:         []string{"node_modules"},
			Reason:             "Node tooling generates these build and cache directories.",
			Consequence:        "Deleting them may require a rebuild or rerun of tests.",
			CleanableByDefault: true,
			RebuildCost:        "low to medium",
			ReclaimDurability:  "temporary",
			PreferredCleanup:   "Rebuild with the project's package scripts when the artifact is needed again.",
		},
		{
			Name:               "swift-build",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskCautious,
			PathPatterns:       []string{".build"},
			AppliesWhen:        []string{"Package.swift exists"},
			Reason:             "Swift Package Manager writes build products into .build/.",
			Consequence:        "Removing it saves space but forces SwiftPM to rebuild packages and targets.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next swift build or test",
			PreferredCleanup:   "Use SwiftPM's clean flow when you want to discard build artifacts.",
		},
		{
			Name:               "terraform-working-dir",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskCautious,
			PathPatterns:       []string{".terraform"},
			AppliesWhen:        []string{"a .tf file exists in the same project"},
			Reason:             "Terraform stores downloaded providers and working state helpers here.",
			Consequence:        "Removing it may force Terraform to re-initialize providers and modules.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next terraform init",
			PreferredCleanup:   "Use Terraform's own init and cleanup flow for the workspace.",
		},
		{
			Name:               "serverless-build-state",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskCautious,
			PathPatterns:       []string{".serverless"},
			AppliesWhen:        []string{"serverless.yml or serverless.yaml exists"},
			Reason:             "Serverless Framework writes deployment packages and local build state here.",
			Consequence:        "Removing it may force packaging work before the next deploy.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next serverless package or deploy",
			PreferredCleanup:   "Let Serverless rebuild packages when they are needed again.",
		},
		{
			Name:               "gradle-build-output",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskCautious,
			PathPatterns:       []string{"build"},
			AppliesWhen:        []string{"build.gradle, build.gradle.kts, settings.gradle, or settings.gradle.kts exists"},
			Reason:             "Gradle writes compiled outputs and generated build files into build/.",
			Consequence:        "Removing it saves space but forces Gradle to rebuild project outputs.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next gradle build or test",
			PreferredCleanup:   "Use Gradle clean when you want to discard build outputs.",
		},
		{
			Name:               "maven-target",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskCautious,
			PathPatterns:       []string{"target"},
			AppliesWhen:        []string{"pom.xml exists"},
			Reason:             "Maven writes compiled outputs and packaged artifacts into target/.",
			Consequence:        "Removing it saves space but forces Maven to rebuild project outputs.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next maven build or test",
			PreferredCleanup:   "Use mvn clean when you want to discard build outputs.",
		},
		{
			Name:               "node-modules",
			Source:             "built-in",
			Category:           CategoryDependencies,
			Risk:               RiskCautious,
			PathPatterns:       []string{"node_modules"},
			AppliesWhen:        []string{"package.json or a known lockfile exists"},
			Exclusions:         []string{},
			Reason:             "Node package managers install dependencies here.",
			Consequence:        "Deleting it saves space but requires reinstalling dependencies.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next install",
			PreferredCleanup:   "Use the project's package manager install flow when dependencies are needed again.",
		},
		{
			Name:               "composer-vendor",
			Source:             "built-in",
			Category:           CategoryDependencies,
			Risk:               RiskCautious,
			PathPatterns:       []string{"vendor"},
			AppliesWhen:        []string{"composer.json exists"},
			Exclusions:         []string{},
			Reason:             "Composer installs PHP dependencies here.",
			Consequence:        "Deleting it saves space but requires composer install.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until the next install",
			PreferredCleanup:   "Use Composer's install flow when dependencies are needed again.",
		},
		{
			Name:               "rust-target",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskCautious,
			PathPatterns:       []string{"target"},
			AppliesWhen:        []string{"Cargo.toml exists"},
			Exclusions:         []string{},
			Reason:             "Rust builds compile into target/. It is generated, but rebuilds can be expensive.",
			Consequence:        "Removing it saves space but forces Cargo to rebuild project artifacts.",
			CleanableByDefault: false,
			RebuildCost:        "medium to high",
			ReclaimDurability:  "until the next cargo build or test",
			PreferredCleanup:   "Use Cargo's own clean flow when you want to discard build artifacts.",
		},
		{
			Name:               "explicit-package-cache",
			Source:             "built-in",
			Category:           CategoryPackageManager,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.npm", "~/.pnpm-store", "~/.yarn", "~/.composer/cache", "npm-cache", "pnpm-store", "yarn-cache", "composer-cache"},
			AppliesWhen:        []string{"the cache path is explicitly scanned or inside an explicitly scanned root"},
			Exclusions:         []string{},
			Reason:             "Known package cache paths can usually be rebuilt by package managers.",
			Consequence:        "Deleting them may make the next install download packages again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until packages are downloaded again",
			PreferredCleanup:   "Use the owning package manager's cache clean or prune flow.",
		},
		{
			Name:               "homebrew-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/Library/Caches/Homebrew"},
			AppliesWhen:        []string{"the Homebrew cache path is explicitly scanned or found under an explicit cache root"},
			Reason:             "Homebrew stores downloaded bottles and source archives here.",
			Consequence:        "Deleting it may make the next brew install or upgrade download packages again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until Homebrew downloads packages again",
			PreferredCleanup:   "Use brew cleanup when you want Homebrew to prune its own cache.",
		},
		{
			Name:               "cypress-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/Library/Caches/Cypress", "~/.cache/Cypress"},
			AppliesWhen:        []string{"the Cypress cache path is explicitly scanned or found under an explicit cache root"},
			Reason:             "Cypress stores downloaded browser binaries here.",
			Consequence:        "Deleting it may make the next Cypress run download browsers again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until Cypress downloads browsers again",
			PreferredCleanup:   "Use Cypress cache commands when you want Cypress to prune its own binaries.",
		},
		{
			Name:               "playwright-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/Library/Caches/ms-playwright", "~/.cache/ms-playwright"},
			AppliesWhen:        []string{"the Playwright cache path is explicitly scanned or found under an explicit cache root"},
			Reason:             "Playwright stores downloaded browser binaries here.",
			Consequence:        "Deleting it may make the next Playwright run download browsers again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until Playwright downloads browsers again",
			PreferredCleanup:   "Use Playwright's browser install tooling when browsers are needed again.",
		},
		{
			Name:               "puppeteer-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/Library/Caches/puppeteer", "~/.cache/puppeteer"},
			AppliesWhen:        []string{"the Puppeteer cache path is explicitly scanned or found under an explicit cache root"},
			Reason:             "Puppeteer stores downloaded browser binaries here.",
			Consequence:        "Deleting it may make the next Puppeteer run download browsers again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until Puppeteer downloads browsers again",
			PreferredCleanup:   "Use the owning Node tooling to reinstall browser binaries when needed.",
		},
		{
			Name:               "npm-cache",
			Source:             "built-in",
			Category:           CategoryPackageManager,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.npm", "npm-cache"},
			AppliesWhen:        []string{"the npm cache path is explicitly scanned or found under an explicit cache root"},
			Reason:             "npm stores downloaded package tarballs and metadata here.",
			Consequence:        "Deleting it may make the next npm install download packages again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until npm downloads packages again",
			PreferredCleanup:   "Use npm cache clean or verify when npm's cache is the actual problem.",
		},
		{
			Name:               "composer-cache",
			Source:             "built-in",
			Category:           CategoryPackageManager,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.composer/cache", "composer-cache"},
			AppliesWhen:        []string{"the Composer cache path is explicitly scanned or found under an explicit cache root"},
			Reason:             "Composer stores downloaded PHP packages and metadata here.",
			Consequence:        "Deleting it may make the next composer install download packages again.",
			CleanableByDefault: false,
			RebuildCost:        "medium",
			ReclaimDurability:  "until Composer downloads packages again",
			PreferredCleanup:   "Use composer clear-cache when Composer's cache is the actual problem.",
		},
		{
			Name:               "explicit-application-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/Library/Caches/*", "~/.cache/*"},
			AppliesWhen:        []string{"the cache directory is explicitly scanned"},
			Exclusions:         []string{"Photos Library.photoslibrary", "database files", ".env", "documents", "downloads"},
			Reason:             "Application cache directories are usually rebuildable, but ownership varies.",
			Consequence:        "Deleting them may log apps out, trigger downloads, or slow the next launch.",
			CleanableByDefault: false,
			RebuildCost:        "unknown",
			ReclaimDurability:  "varies by app",
			PreferredCleanup:   "Review the owning app before clearing its cache.",
		},
		{
			Name:               "unknown-large-file",
			Source:             "built-in",
			Category:           CategoryUnknownLargeFiles,
			Risk:               RiskDangerous,
			PathPatterns:       []string{"files >= 100 MiB outside known generated rules"},
			AppliesWhen:        []string{"file is not under a protected or known personal path"},
			Exclusions:         []string{"documents", "photos", "videos", "downloads", "archives", "database dumps", ".env", "database files"},
			Reason:             "Large unknown files are worth seeing, not guessing about.",
			Consequence:        "Report-only. Ratatoskr will not clean this by default.",
			CleanableByDefault: false,
			RebuildCost:        "unknown",
			ReclaimDurability:  "unknown",
			PreferredCleanup:   "Inspect the file and decide outside Ratatoskr.",
		},
		{
			Name:               "ollama-model-blob",
			Source:             "built-in",
			Category:           CategoryLocalAIModels,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.ollama/models/blobs/*"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Exclusions:         []string{},
			Reason:             "Ollama stores downloaded model layers here. They can be large and usually re-downloadable.",
			Consequence:        "Do not delete random blob files by hand. Use Ollama's model list/remove flow so references stay consistent.",
			CleanableByDefault: false,
			RebuildCost:        "high",
			ReclaimDurability:  "until the model is downloaded again",
			PreferredCleanup:   "Use Ollama's model management flow for models you recognize.",
		},
		{
			Name:               "lm-studio-model-file",
			Source:             "built-in",
			Category:           CategoryLocalAIModels,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.cache/lm-studio/models/**/*.gguf", "~/Library/Application Support/LM Studio/models/**/*.gguf"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Exclusions:         []string{},
			Reason:             "LM Studio stores local model files here. They can be large and usually re-downloadable.",
			Consequence:        "Treat this as removing a specific local model, not cleaning a generic cache. Delete only models you recognize.",
			CleanableByDefault: false,
			RebuildCost:        "high",
			ReclaimDurability:  "until the model is downloaded again",
			PreferredCleanup:   "Use LM Studio's model management UI for models you recognize.",
		},
		{
			Name:               "dbngin-database-state",
			Source:             "built-in",
			Category:           CategoryDatabaseState,
			Risk:               RiskDangerous,
			PathPatterns:       []string{"~/Library/Application Support/com.tinyapp.DBngin/Engines/*/data/**"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Reason:             "DBngin stores local database state here.",
			Consequence:        "Report-only. Deleting database state can destroy local databases.",
			CleanableByDefault: false,
			RebuildCost:        "unknown",
			ReclaimDurability:  "unknown",
			PreferredCleanup:   "Use DBngin or the database engine's own backup and removal flow.",
		},
		{
			Name:               "dbngin-engine-recovery-state",
			Source:             "built-in",
			Category:           CategoryDatabaseState,
			Risk:               RiskDangerous,
			PathPatterns:       []string{"~/Library/Application Support/com.tinyapp.DBngin/Engines/*/{broken,recovery}/**"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Reason:             "DBngin keeps broken or recovery engine folders near real database state.",
			Consequence:        "Report-only. These folders may contain the only recoverable copy of a local database.",
			CleanableByDefault: false,
			RebuildCost:        "unknown",
			ReclaimDurability:  "unknown",
			PreferredCleanup:   "Inspect DBngin and backup the database before removing recovery files.",
		},
		{
			Name:               "chrome-on-device-model",
			Source:             "built-in",
			Category:           CategoryBrowserModels,
			Risk:               RiskDangerous,
			PathPatterns:       []string{"~/Library/Application Support/Google/Chrome/**/OptimizationGuidePredictionModels/**"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Reason:             "Chrome stores on-device model weights for browser features here.",
			Consequence:        "Report-only. Removing browser model state may make Chrome download model files again or disable local features until it does.",
			CleanableByDefault: false,
			RebuildCost:        "medium to high",
			ReclaimDurability:  "until Chrome downloads model files again",
			PreferredCleanup:   "Use Chrome's own settings or leave the model store alone unless you know why it is large.",
		},
		{
			Name:               "cursor-snapshot-state",
			Source:             "built-in",
			Category:           CategoryApplicationState,
			Risk:               RiskDangerous,
			PathPatterns:       []string{"~/Library/Application Support/Cursor/**/snapshots/**"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Reason:             "Cursor snapshots may hold editor recovery state.",
			Consequence:        "Report-only. Removing them can discard recoverable editor state.",
			CleanableByDefault: false,
			RebuildCost:        "unknown",
			ReclaimDurability:  "unknown",
			PreferredCleanup:   "Review Cursor's state from the app before removing snapshots.",
		},
	}
}

func protectedLaravelExclusions() []string {
	return []string{
		"storage/app",
		"storage/framework/sessions",
		"database/*.sqlite",
		".env",
		"public/uploads",
		"public/storage",
	}
}
