package ratatoskr

func BuiltInRules() []Rule {
	return []Rule{
		{
			Name:               "laravel-storage-logs",
			Source:             "built-in",
			Category:           CategoryLogs,
			Risk:               RiskSafe,
			PathPatterns:       []string{"storage/logs/*.log"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel writes these logs during normal runtime.",
			Consequence:        "Deleting them removes local log history. Laravel recreates new logs when needed.",
			CleanableByDefault: true,
		},
		{
			Name:               "laravel-bootstrap-cache",
			Source:             "built-in",
			Category:           CategoryFrameworkRuntime,
			Risk:               RiskSafe,
			PathPatterns:       []string{"bootstrap/cache/*.php"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel generates these framework cache files.",
			Consequence:        "Deleting them may make the next Laravel command rebuild framework cache.",
			CleanableByDefault: true,
		},
		{
			Name:               "laravel-compiled-views",
			Source:             "built-in",
			Category:           CategoryFrameworkRuntime,
			Risk:               RiskSafe,
			PathPatterns:       []string{"storage/framework/views/*"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel compiles Blade templates into this directory.",
			Consequence:        "Deleting them may make the next request recompile views.",
			CleanableByDefault: true,
		},
		{
			Name:               "laravel-framework-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskSafe,
			PathPatterns:       []string{"storage/framework/cache/*"},
			AppliesWhen:        []string{"artisan exists", "composer.json requires laravel/framework"},
			Exclusions:         protectedLaravelExclusions(),
			Reason:             "Laravel stores generated framework cache entries here.",
			Consequence:        "Deleting them may make Laravel rebuild cache entries.",
			CleanableByDefault: true,
		},
		{
			Name:               "node-build-output",
			Source:             "built-in",
			Category:           CategoryBuilds,
			Risk:               RiskSafe,
			PathPatterns:       []string{".next", "dist", "build", ".turbo", ".vite", "coverage"},
			AppliesWhen:        []string{"package.json or a known lockfile exists"},
			Exclusions:         []string{"node_modules"},
			Reason:             "Node tooling generates these build and cache directories.",
			Consequence:        "Deleting them may require a rebuild or rerun of tests.",
			CleanableByDefault: true,
		},
		{
			Name:               "node-modules",
			Source:             "built-in",
			Category:           CategoryDependencies,
			Risk:               RiskCautious,
			PathPatterns:       []string{"node_modules"},
			AppliesWhen:        []string{"package.json or a known lockfile exists"},
			Exclusions:         []string{},
			Reason:             "Node package managers install dependencies here.",
			Consequence:        "Deleting it saves space but requires reinstalling dependencies.",
			CleanableByDefault: false,
		},
		{
			Name:               "composer-vendor",
			Source:             "built-in",
			Category:           CategoryDependencies,
			Risk:               RiskCautious,
			PathPatterns:       []string{"vendor"},
			AppliesWhen:        []string{"composer.json exists"},
			Exclusions:         []string{},
			Reason:             "Composer installs PHP dependencies here.",
			Consequence:        "Deleting it saves space but requires composer install.",
			CleanableByDefault: false,
		},
		{
			Name:               "explicit-package-cache",
			Source:             "built-in",
			Category:           CategoryPackageManager,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.npm", "~/.pnpm-store", "~/.yarn", "~/.composer/cache", "npm-cache", "pnpm-store", "yarn-cache", "composer-cache"},
			AppliesWhen:        []string{"the cache path is explicitly scanned or inside an explicitly scanned root"},
			Exclusions:         []string{},
			Reason:             "Known package cache paths can usually be rebuilt by package managers.",
			Consequence:        "Deleting them may make the next install download packages again.",
			CleanableByDefault: false,
		},
		{
			Name:               "explicit-application-cache",
			Source:             "built-in",
			Category:           CategoryCaches,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/Library/Caches/*", "~/.cache/*"},
			AppliesWhen:        []string{"the cache directory is explicitly scanned"},
			Exclusions:         []string{"Photos Library.photoslibrary", "database files", ".env", "documents", "downloads"},
			Reason:             "Application cache directories are usually rebuildable, but ownership varies.",
			Consequence:        "Deleting them may log apps out, trigger downloads, or slow the next launch.",
			CleanableByDefault: false,
		},
		{
			Name:               "unknown-large-file",
			Source:             "built-in",
			Category:           CategoryUnknownLargeFiles,
			Risk:               RiskDangerous,
			PathPatterns:       []string{"files >= 100 MiB outside known generated rules"},
			AppliesWhen:        []string{"file is not under a protected or known personal path"},
			Exclusions:         []string{"documents", "photos", "videos", "downloads", "archives", "database dumps", ".env", "database files"},
			Reason:             "Large unknown files are worth seeing, not guessing about.",
			Consequence:        "Report-only. Ratatoskr will not clean this by default.",
			CleanableByDefault: false,
		},
		{
			Name:               "ollama-model-blob",
			Source:             "built-in",
			Category:           CategoryLocalAIModels,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.ollama/models/blobs/*"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Exclusions:         []string{},
			Reason:             "Ollama stores downloaded model layers here. They can be large and usually re-downloadable.",
			Consequence:        "Do not delete random blob files by hand. Use Ollama's model list/remove flow so references stay consistent.",
			CleanableByDefault: false,
		},
		{
			Name:               "lm-studio-model-file",
			Source:             "built-in",
			Category:           CategoryLocalAIModels,
			Risk:               RiskCautious,
			PathPatterns:       []string{"~/.cache/lm-studio/models/**/*.gguf", "~/Library/Application Support/LM Studio/models/**/*.gguf"},
			AppliesWhen:        []string{"path is inside an explicitly scanned tree"},
			Exclusions:         []string{},
			Reason:             "LM Studio stores local model files here. They can be large and usually re-downloadable.",
			Consequence:        "Treat this as removing a specific local model, not cleaning a generic cache. Delete only models you recognize.",
			CleanableByDefault: false,
		},
	}
}

func protectedLaravelExclusions() []string {
	return []string{
		"storage/app",
		"storage/framework/sessions",
		"database/*.sqlite",
		".env",
		"public/uploads",
		"public/storage",
	}
}
